name: Deploy para Alwaysdata

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp-loxaid.alwaysdata.net
          username: ${{ secrets.ALWAYSDATA_USER }}
          password: ${{ secrets.ALWAYSDATA_PASSWORD }}
          # Ajuste o caminho abaixo para a pasta do seu site
          server-dir: www/loxaid.alwaysdata.net/agencia-led
          protocol: sftp
          port: 22