name: Deploy para Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # KEY (Parâmetro) : VALUE (Variável/Secret)
          server: ${{ secrets.ALWAYSDATA_SERVER }}
          username: ${{ secrets.ALWAYSDATA_USER }}
          password: ${{ secrets.ALWAYSDATA_PASSWORD }}
          port: 22
          local_path: './'              # Sobe tudo da pasta atual
          remote_path: '/www/loxaid.alwaysdata.net/' # Destino final
          sftp_only: true