name: Deploy para Agencia LED

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SFTP (Pasta agencia-led)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ALWAYSDATA_SERVER }}
          username: ${{ secrets.ALWAYSDATA_USER }}
          password: ${{ secrets.ALWAYSDATA_PASSWORD }}
          port: 22
          local_path: './'
          # Enviando para a subpasta que você pediu:
          remote_path: 'www/agencia-led/' 
          sftp_only: true
          # Isso ignora erros de permissão em arquivos ocultos (como o .git)
          # e foca em subir o seu PHP e Assets
          ssh_options: '-o StrictHostKeyChecking=no'